Upgrade to substrate v1.0.0 (#264)
### Description
<!-- Describe what change this PR is implementing -->
Supersedes #263  

### Types of Changes
<!--- What types of changes does your code introduce? -->
- [ ] Tech Debt (Code improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [x] Dependency upgrade (A change in substrate or any 3rd party crate
version)

### Migrations and Hooks
<!--- Check the following box with an x if the following applies: -->
- [x] This change requires a runtime migration.
- [ ] Modifies `on_initialize`
- [ ] Modifies `on_finalize`

### Checklist
<!--- All boxes need to be checked. Follow this checklist before
requiring PR review -->
- [x] Change has been tested locally.
- [ ] Change adds / updates tests.
- [x] Changelog doc updated.

### TODO
- [x] Fix contracts migration failing with try-runtime
```
panicked at 'called `Result::unwrap()` on an `Err` value: Other("deposit mismatch")', /home/rakan/.cargo/git/checkouts/substrate-7e08433d4c370a21/948fbd2/frame/contracts/src/migration.rs:296:35
```
- [x] Add missing migrations
- [x] Remove socieyt pallet (#275 )
- [ ] Test upgrade from 0.9.42 to v1.0.0 locally and check if migrations
can execute within the max block weight.